import { createApp } from "vue";
import App from "./App.vue";
// import Example from "./Example.vue";
// import Example2 from "./Example2.vue";
// import Example3 from "./Example3.vue";
// import Example4 from "./Example4.vue";
// import Example5 from "./Example5.vue";
// import Example6 from "./Example6.vue";
import Example7 from "./Example7.vue";
const app = createApp(App);
// const exampleApp = createApp(Example);
// const exampleApp2 = createApp(Example2);
// const exampleApp3 = createApp(Example3);
// const exampleApp4 = createApp(Example4);
// const exampleApp5 = createApp(Example5);
// const exampleApp6 = createApp(Example6);
const exampleApp7 = createApp(Example7);
app.mount('#app');
// exampleApp.mount('#example');
// exampleApp2.mount('#example2');
// exampleApp3.mount('#example3');
// exampleApp4.mount('#example4');
// exampleApp5.mount('#example5');
// exampleApp6.mount('#example6');
exampleApp7.mount('#example7');
