import { createApp } from "vue";
import App from "./App.vue";
// import Example from "./Example.vue";
// import Example2 from "./Example2.vue";
// import Example3 from "./Example3.vue";
import Example4 from "./Example4.vue";
const app = createApp(App);
// const exampleApp = createApp(Example);
// const exampleApp2 = createApp(Example2);
// const exampleApp3 = createApp(Example3);
const exampleApp4 = createApp(Example4);
app.mount('#app');
// exampleApp.mount('#example');
// exampleApp2.mount('#example2');
// exampleApp3.mount('#example3');
exampleApp4.mount('#example4');
